MilestoneForm #43 Closed
UNICEFECAR/parent-buddy-mobile pull request #45
Opened 2020-06-11 13:04 UTC by MilosByteOut

2020-06-11 13:58 UTC, MilosByteOut commented
Development info #44 

Tekst je html i treba da bude translatable? Ne znam da li treba jos nesto da ubacim ili samo html, posto kapiram da ce svakako da se vuce dinamicno tekst na onom jeziku koji nama treba, ne znam da li ima neka druga funkcija koja ce napraviti da bude translatable?

2020-06-11 14:32 UTC, MilosByteOut commented
Milestone Card #42 

Article sam smestio u state u slucaju da ih ima u props-u. 
Ali za text button nisam siguran da li bi trebalo da bude niz?? 

Ukoliko dobro kapiram ovo su sve textButton-i 
https://prnt.sc/sxyggg

2020-06-11 14:39 UTC, violinista commented
Jeste, moze da bude i niz koji sadrzi text i link

2020-06-11 14:53 UTC, mi5ha commented
> Milestone Card #42
> 
> Article sam smestio u state u slucaju da ih ima u props-u.
> Ali za text button nisam siguran da li bi trebalo da bude niz??
> 
> Ukoliko dobro kapiram ovo su sve textButton-i
> https://prnt.sc/sxyggg

Ako pogledas sve moguce varijante ove kartice, videces da ima ovo:

<img width="272" alt="Screen Shot 2020-06-11 at 4 51 20 PM" src="https://user-images.githubusercontent.com/1238203/84401679-d6645380-ac03-11ea-9c7a-75ebb2b4e2fc.png">

Za rounded button imas prop: roundedButton

Za ovaj text button ispod njega imas prop: textButton

<img width="255" alt="Screen Shot 2020-06-11 at 4 51 31 PM" src="https://user-images.githubusercontent.com/1238203/84401797-f8f66c80-ac03-11ea-9f2a-a88b9bb92934.png">

Za ove linkove (text button) ka clancima imas prop: articles

2020-06-11 21:33 UTC, mi5ha requested changes

2020-06-11 21:33 UTC, mi5ha commented on mobile/src/components/development/MilestoneForm.tsx
> +                                left={props => <Checkbox status={item.checked ? 'checked' : 'unchecked'} color="#2BABEE" onPress={() => { }} />}
Zameni svugde Checkbox sa Checkbox.Android

Ako se stavi samo Checkbox onda checkbox izgleda drugacije na iOSu i na Androidu a oni hoce Android look uvek

2020-06-11 21:33 UTC, mi5ha commented on mobile/src/components/development/MilestoneForm.tsx
> +                                left={props => <Checkbox status={item.checked ? 'checked' : 'unchecked'} color="#2BABEE" onPress={() => { }} />}
Vidm da ne mogu da kliknem checkbox. Korisnik mora da moze da klikne checkbox i promeni mu stanje. A ako kliknes text, otvori se accordion.

2020-06-11 21:33 UTC, mi5ha commented on mobile/src/components/development/DevelopmentInfo.tsx
> +const htmlStyles = {
Probaj da line height bude slican kao u designu, tamo ima mnogo manje spacea izmedju linija.

2020-06-16 10:26 UTC, mi5ha requested changes

2020-06-16 10:26 UTC, mi5ha commented on mobile/src/components/development/MilestoneCard.tsx
>  import React, { Component } from 'react'
Padding dole na MilestoneCard je suvise veliki, top i bottom paddinzi treba da su slicni.

Ovo je problem i na:

<img width="263" alt="Screen Shot 2020-06-16 at 12 22 09 PM" src="https://user-images.githubusercontent.com/1238203/84763136-075dd300-afcc-11ea-9742-07417f917e13.png">

Vidi jel jos negde ima taj problem.

2020-06-16 10:26 UTC, mi5ha commented on mobile/src/components/development/MilestoneForm.stories.tsx
>  import { View } from 'react-native';
Kad se klikne checkbox na iosu on ne menja stanje. Accordion radi.

2020-06-16 14:19 UTC, mi5ha approved these changes

2020-06-16 14:23 UTC, merged